indicium_webapp/Models/Guest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace indicium_webapp.Models
{
    [Table("Guests")]
    public class Guest
    {
        public Guest()
        {
            SignUps = new HashSet<SignUp>();
        }

        public int GuestID { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Name
        {
            get { return FirstName + " " + LastName; }
        }

        public string Email { get; set; }

        public virtual ICollection<SignUp> SignUps { get; set; }
    }
}

indicium_webapp/Models/SignUp.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Net;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace indicium_webapp.Models
{
    [Table("SignUps")]
    public class SignUp
    {
        public int SignUpID { get; set; }

        public int ActivityID { get; set; }

        public Activity Activity { get; set; }

        public string ApplicationUserID { get; set; }

        public ApplicationUser ApplicationUser { get; set; }

        public int? GuestID { get; set; }

        public Guest Guest { get; set; }

        // Validation to make sure there's at least a ApplicationUser or Guest coupled to the signup
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (ApplicationUser == null || Guest == null)
            {
                yield return new ValidationResult("Er moet een gast of gebruiker zijn gekoppeld aan de inschrijving.");
            }
        }
    }

}

indicium_webapp/Models/ViewModels/AccountViewModels/GuestViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace indicium_webapp.Models.ViewModels.AccountViewModels
{
    public class GuestViewModel
    {
        public int GuestID { get; set; }
        
        [Required(ErrorMessage = "{0} is verplicht.")]
        [StringLength(50, ErrorMessage = "{0} mag maximaal {1} karakter(s) zijn.")]
        [Display(Name = "Voornaam")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "{0} is verplicht.")]
        [StringLength(100, ErrorMessage = "{0} mag maximaal {1} karakter(s) zijn.")]
        [Display(Name = "Achternaam")]
        public string LastName { get; set; }

        [Display(Name = "Naam")]
        public string Name
        {
            get { return FirstName + " " + LastName; }
        }

        [Required(ErrorMessage = "{0} is verplicht.")]
        [EmailAddress]
        [Display(Name = "E-mailadres")] 
        public string Email { get; set; }

    }
}

indicium_webapp/Models/ViewModels/SignUpViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using indicium_webapp.Models.ViewModels.AccountViewModels;
using indicium_webapp.Models.ViewModels;
using indicium_webapp.Models;

namespace indicium_webapp.Models.ViewModels
{
    public class SignUpViewModel
    {
        public int SignUpID { get; set; }

        public ActivityViewModel Activity { get; set; }

        public ApplicationUserViewModel ApplicationUser { get; set; }

        public GuestViewModel Guest { get; set; }

    }
}

indicium_webapp/Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using indicium_webapp.Data;
using indicium_webapp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Globalization;
using indicium_webapp.Models.ViewModels;

namespace indicium_webapp.Controllers
{
    [Route("activiteiten"), Authorize(Roles = "Bestuur, Secretaris")]
    public class ActivitiesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public ActivitiesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public enum ActivityMessageId
        {
            GuestSignUpSuccess
        }

        // GET: /activiteiten
        public async Task<IActionResult> Index()
        {
            var activitiesResult = await _context.Activity.Include(activity => activity.SignUps).ToListAsync();
            IEnumerable<ActivityViewModel> model = activitiesResult.Select(CreateActivitiesViewModel);

            return View(model);
        }

        // GET: /activiteiten/details/{id}
        [AllowAnonymous, Route("details/{id}")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activityResult = await _context.Activity
                .Include(activity => activity.SignUps).ThenInclude(activity => activity.ApplicationUser)
                .Include(activity => activity.SignUps).ThenInclude(activity => activity.Guest)
                .Include(activity => activity.ActivityType)
                .SingleOrDefaultAsync(activity => activity.ActivityID == id);
            
            if (activityResult == null)
            {
                return NotFound();
            }

            ActivityViewModel model = CreateActivitiesViewModel(activityResult);

            if (_signInManager.IsSignedIn(User))
            {
                ViewBag.LoggedInUserSignedUp = model.SignUps.Any(signUps => signUps.ApplicationUserID == _userManager.GetUserAsync(User).Result.Id);
                ViewBag.ApplicationUsersSignedUpCount = model.SignUps.Where(signUps => signUps.ApplicationUserID != null).Count();
                ViewBag.GuestsSignedUpCount = model.SignUps.Where(signUps => signUps.Guest != null).Count();
            }

            return View(model);
        }

        // GET: /activiteiten/aanmaken
        [Route("aanmaken")]
        public IActionResult Create()
        {
            var activityTypesResult = _context.ActivityType.ToListAsync().Result;
            ViewBag.ActivityTypes = new SelectList(activityTypesResult, "ActivityTypeID", "Name");

            return View();
        }

        // POST: /activiteiten/aanmaken
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateAntiForgeryToken, Route("aanmaken")]
        public async Task<IActionResult> Create(ActivityViewModel model)
        {
            if (ModelState.IsValid)
            {
                _context.Add(CreateActivity(model));
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            var activityTypesResult = _context.ActivityType.ToListAsync().Result;
            ViewBag.ActivityTypes = new SelectList(activityTypesResult, "ActivityTypeID", "Name");

            return View(model);
        }

        // GET: /activiteiten/bewerken/{id}
        [Route("bewerken/{id}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activityResult = await _context.Activity
                .Include(activity => activity.ActivityType)
                .SingleOrDefaultAsync(activity => activity.ActivityID == id);
            
            var activityTypeResult = _context.ActivityType.SingleOrDefault(activityType => activityType.ActivityTypeID == activityResult.ActivityTypeID);
            
            if (activityResult == null)
            {
                return NotFound();
            }

            var activityTypesResult = _context.ActivityType.ToListAsync().Result;
            ViewBag.ActivityTypes = new SelectList(activityTypesResult, "ActivityTypeID", "Name", activityTypeResult.ActivityTypeID);

            return View(CreateActivitiesViewModel(activityResult));
        }

        // POST: /activiteiten/bewerken/{id}
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, Route("bewerken/{id}"), ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ActivityViewModel model)
        {
            if (id != model.ActivityID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (!model.NeedsSignUp)
                    {
                        var signUps = _context.SignUp.Where(signUp => signUp.ActivityID == model.ActivityID && (signUp.ApplicationUserID == GetCurrentUserAsync().Id || signUp.GuestID != null));
                        foreach (var signup in signUps)
                        {
                            _context.SignUp.Remove(signup);
                        }

                        await _context.SaveChangesAsync();
                    }
                    
                    _context.Update(CreateActivity(model));
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActivityTypeExists(model.ActivityID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction("Index");
            }

            var activityResult = await _context.Activity
                .Include(activity => activity.ActivityType)
                .SingleOrDefaultAsync(activity => activity.ActivityID == id);
            
            var activityTypeResult = _context.ActivityType.SingleOrDefault(activityType => activityType.ActivityTypeID == activityResult.ActivityTypeID);
            
            if (activityResult == null)
            {
                return NotFound();
            }
            
            var activityTypesResult = _context.ActivityType.ToListAsync().Result;
            ViewBag.ActivityTypes = new SelectList(activityTypesResult, "ActivityTypeID", "Name", activityTypeResult.ActivityTypeID);

            return View(model);
        }

        // GET: /activiteiten/verwijderen/{id}
        [Route("verwijderen/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activityResult = await _context.Activity
                .Include(activity => activity.ActivityType)
                .SingleOrDefaultAsync(activity => activity.ActivityID == id);

            if (activityResult == null)
            {
                return NotFound();
            }

            return View(CreateActivitiesViewModel(activityResult));
        }

        // POST: /activiteiten/verwijderen/{id}
        [HttpPost, ActionName("Delete"), ValidateAntiForgeryToken, Route("verwijderen/{id}")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var activityResult = await _context.Activity.SingleOrDefaultAsync(activity => activity.ActivityID == id);

            _context.Activity.Remove(activityResult);
            await _context.SaveChangesAsync();
            
            return RedirectToAction("Index");
        }

        // GET: /activiteiten/kalender
        [AllowAnonymous, Route("kalender")]
        public IActionResult Calendar(ActivityMessageId? message = null)
        {
            ViewData["StatusMessage"] = message == ActivityMessageId.GuestSignUpSuccess ? "Je inschrijving is gelukt." : "";
            
            return View();
        }

        private bool ActivityTypeExists(int id)
        {
            return _context.Activity.Any(activity => activity.ActivityTypeID == id);
        }

        private ApplicationUser GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(User).Result;
        }

        private Activity CreateActivity(ActivityViewModel model)
        {
            var activityTypeResult = _context.ActivityType.SingleOrDefault(activityType => activityType.ActivityTypeID == Convert.ToInt32(model.ActivityTypeID));
            
            return new Activity
            {
                ActivityID = model.ActivityID,
                Name = model.Name,
                Description = model.Description,
                StartDateTime = DateTime.ParseExact(model.StartDateTime, "dd-MM-yyyy HH:mm", new CultureInfo("nl-NL")),
                EndDateTime = DateTime.ParseExact(model.EndDateTime, "dd-MM-yyyy HH:mm", new CultureInfo("nl-NL")),
                NeedsSignUp = model.NeedsSignUp,
                ActivityType = activityTypeResult
            };
        }
        

indicium_webapp/Views/SignUps/Delete.cshtml
@model SignUpViewModel

@{
    ViewData["Title"] = "Inschrijving verwijderen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Inschrijving verwijderen</h2>

<h3>Weet je zeker dat je wilt uitschrijven?</h3>
<div>
    <h4>Inschrijving</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="SignUpID" />
        <dt>
            @Html.DisplayNameFor(model => model.Activity.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Activity.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Activity.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Activity.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Activity.StartDateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Activity.StartDateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Activity.EndDateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Activity.EndDateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Activity.NeedsSignUp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Activity.NeedsSignUp)
        </dd>
        <br/>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.Sex)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Sex)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.Birthday)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Birthday)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.AddressStreet)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.AddressStreet)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.AddressNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.AddressNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.AddressPostalCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.AddressPostalCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.AddressCity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.AddressCity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.AddressCountry)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.AddressCountry)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.StudentNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.StudentNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.StartdateStudy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.StartdateStudy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.StudyType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.StudyType)
        </dd>
    </dl>

    <form asp-action="delete" asp-route-id="@Model.Activity.ActivityID" method="post">
        <div class="form-actions no-color">
            <button type="submit" class="btn btn-danger">Bevestig uitschrijving</button>
            <a asp-action="Index" class="btn btn-default">Terug naar overzicht</a>
        </div>
    </form>
</div>

indicium_webapp/Views/SignUps/Details.cshtml
@model SignUpViewModel

@{
    ViewData["Title"] = "Inschrijving details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Inschrijving details</h2>

<div>
    <h4>Inschrijving</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Activity.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Activity.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Activity.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Activity.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Activity.StartDateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Activity.StartDateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Activity.EndDateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Activity.EndDateTime)
        </dd>
        <br/>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.Sex)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Sex)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.Birthday)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Birthday)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.AddressStreet)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.AddressStreet)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.AddressNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.AddressNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.AddressPostalCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.AddressPostalCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.AddressCity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.AddressCity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.AddressCountry)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.AddressCountry)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.StudentNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.StudentNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.StartdateStudy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.StartdateStudy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.StudyType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.StudyType)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Activities" asp-action="Details" asp-route-id="@Model.Activity.ActivityID" class="btn btn-default">Terug naar activiteitdetails</a>
    <a asp-action="Index" class="btn btn-default">Terug naar overzicht</a>
</div>

indicium_webapp/Views/SignUps/Guest.cshtml
@model SignUpViewModel

@addTagHelper *, PaulMiami.AspNetCore.Mvc.Recaptcha

@{
    ViewData["Title"] = "Inschrijven";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var ActivityName = @Model.Activity.Name;
}

<h2>Inschrijven voor @ActivityName</h2>

<form asp-action="guest" asp-route-id="@Model.Activity.ActivityID" class="form-horizontal">
    <h4>Activiteit</h4>
    <hr />
    
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    
    <h5>Persoonsgegevens:</h5>
    <div class="form-group">
        <label asp-for="Guest.FirstName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Guest.FirstName" class="form-control" />
            <span asp-validation-for="Guest.FirstName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Guest.LastName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Guest.LastName" class="form-control" />
            <span asp-validation-for="Guest.LastName" class="text-danger"></span>
        </div>
    </div>      
    <div class="form-group">
        <label asp-for="Guest.Email" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Guest.Email" class="form-control" />
            <span asp-validation-for="Guest.Email" class="text-danger"></span>
        </div>
    </div>

    <h5>Activiteitgegevens:</h5>
    <div class="form-group">
        <label class="col-md-2 control-label">@Html.DisplayNameFor(model => model.Activity.Name)</label>
        <div class="col-md-10">
            <p class="form-control-static">@Html.DisplayFor(model => model.Activity.Name)</p>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">@Html.DisplayNameFor(model => model.Activity.Description)</label>
        <div class="col-md-10">
            <p class="form-control-static">@Html.DisplayFor(model => model.Activity.Description)</p>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">@Html.DisplayNameFor(model => model.Activity.StartDateTime)</label>
        <div class="col-md-10">
            <p class="form-control-static">@Html.DisplayFor(model => model.Activity.StartDateTime)</p>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">@Html.DisplayNameFor(model => model.Activity.EndDateTime)</label>
        <div class="col-md-10">
            <p class="form-control-static">@Html.DisplayFor(model => model.Activity.EndDateTime)</p>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">@Html.DisplayNameFor(model => model.Activity.ActivityType)</label>
        <div class="col-md-10">
            <p class="form-control-static">@Html.DisplayFor(model => model.Activity.ActivityType.Name)</p>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">@Html.DisplayNameFor(model => model.Activity.NeedsSignUp)</label>
        <div class="col-md-10">
            <p class="form-control-static">@Html.DisplayFor(model => model.Activity.NeedsSignUp)</p>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <recaptcha />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Inschrijving bevestigen" class="btn btn-default" />
        </div>
    </div>
</form>

<div>
    <a asp-controller="activities" asp-action="calendar">Terug naar overzicht</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <recaptcha-script />
}

indicium_webapp/Views/SignUps/Index.cshtml
@model IEnumerable<SignUpViewModel>

@{
    ViewData["Title"] = "Inschrijvingen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Inschrijvingen</h2>

@if (Model != null && Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Activity.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Activity.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Activity.StartDateTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Activity.EndDateTime)
                    </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Activity.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Activity.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Activity.StartDateTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Activity.EndDateTime)
                    </td>
                    <td>
                        <a class="btn btn-success" asp-action="details" asp-route-id="@item.SignUpID"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span></a>
                        <a class="btn btn-danger" asp-action="delete" asp-route-id="@item.Activity.ActivityID">Uitschrijven</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Er zijn geen inschrijvingen gevonden.</p>
}